--------------------------------------------------------
--  File created - Wednesday-September-23-2020   
--------------------------------------------------------
CREATE SEQUENCE ISEQ$$_76071 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76076 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76079 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76082 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76084 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76086 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76088 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76091 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76093 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76096 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76098 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76100 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76102 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76104 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76106 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76108 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76111 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76115 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76117 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76119 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76121 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76123 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76125 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76127 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE ISEQ$$_76129 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
--------------------------------------------------------
--  DDL for Table AREA
--------------------------------------------------------

  CREATE TABLE "AREA" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOME" VARCHAR2(250 BYTE), 
	"TIPOAREA" NUMBER(*,0), 
	"TIPOSTORIA" NUMBER(*,0), 
	"TIPOPOSIZIONE" NUMBER(*,0), 
	"PROGRESSIVO" NUMBER(*,0), 
	"CODICEAREAPROV" VARCHAR2(50 BYTE), 
	"NOTE" VARCHAR2(2048 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table ATTO
--------------------------------------------------------

  CREATE TABLE "ATTO" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NUMATTO" NUMBER(*,0), 
	"DATAATTO" DATE, 
	"IDPIANO" NUMBER(*,0), 
	"TIPOATTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table AUTORIZZAZIONE
--------------------------------------------------------

  CREATE TABLE "AUTORIZZAZIONE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDPIANO" NUMBER(*,0), 
	"IDPIANOAREA" NUMBER(*,0), 
	"IDSTRUTTURA" NUMBER(*,0), 
	"IDESERCENTE" NUMBER(*,0), 
	"TIPORECUPEROMORFOLOGICO" NUMBER(*,0), 
	"TIPORECUPEROFINALE" NUMBER(*,0), 
	"TIPODISPONIBILITA" NUMBER(*,0), 
	"NUMEROATTO" VARCHAR2(15 BYTE), 
	"NUMEROATTONOTIFICA" VARCHAR2(15 BYTE), 
	"VOLUMEAUTORIZZATO" NUMBER(11,2), 
	"PESOAUTORIZZATO" NUMBER(11,2), 
	"SUPERFICIEAUTORIZZATA" NUMBER(11,2), 
	"SUPERFICIESCAVO" NUMBER(11,2), 
	"PROFONDITASCAVO" NUMBER(11,2), 
	"DATAAUTORIZZAZIONE" DATE, 
	"DATANOTIFICA" DATE, 
	"DATASCADENZA" DATE, 
	"DATASISTEMAZIONE" DATE, 
	"DENUNCIAESERCIZION" VARCHAR2(100 BYTE), 
	"DENUNCIAESERCIZIODATA" DATE, 
	"CONVENZIONEN" VARCHAR2(100 BYTE), 
	"CONVENZIONEDATA" DATE, 
	"SOSPENSIONEN" VARCHAR2(100 BYTE), 
	"SOSPENSIONEDATA" DATE, 
	"REVOCAN" VARCHAR2(100 BYTE), 
	"REVOCADATA" DATE, 
	"DECADENZAN" VARCHAR2(100 BYTE), 
	"DECADENZADATA" DATE, 
	"RINUNCIAN" VARCHAR2(100 BYTE), 
	"RINUNCIADATA" DATE, 
	"AUTORIZZAZIONE104N" VARCHAR2(100 BYTE), 
	"AUTORIZZAZIONE104DATA" DATE, 
	"AUTORIZZAZIONE104NOTE" VARCHAR2(2048 BYTE), 
	"VOLUME104" NUMBER(11,2), 
	"SVINCOLOFIDEJUSSIONEN" VARCHAR2(100 BYTE), 
	"SVINCOLOFIDEJUSSIONEDATA" DATE, 
	"SVINCOLOFIDEJUSSIONENOTE" VARCHAR2(2048 BYTE), 
	"COLLAUDON" VARCHAR2(100 BYTE), 
	"COLLAUDODATA" DATE, 
	"COLLAUDONOTE" VARCHAR2(2048 BYTE), 
	"PENDENZASCARPATE" VARCHAR2(100 BYTE), 
	"QUOTAPIANOCAMPAGNA" VARCHAR2(100 BYTE), 
	"PAREREAGENZIA" VARCHAR2(255 BYTE), 
	"VIA" NUMBER(1,0), 
	"SCREENING" NUMBER(1,0), 
	"PAREREMOTIVATO" VARCHAR2(50 BYTE), 
	"PROPRIETATERRENI" VARCHAR2(2048 BYTE), 
	"NOTESISTEMAZIONE" VARCHAR2(2048 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table AUTORIZZAZIONEMATERIALE
--------------------------------------------------------

  CREATE TABLE "AUTORIZZAZIONEMATERIALE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDAUTORIZZAZIONE" NUMBER(*,0), 
	"IDMATERIALE" NUMBER(*,0), 
	"QUANTITAAUTORIZZATA" NUMBER(10,1), 
	"PESOAUTORIZZATO" NUMBER(9,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table COMUNE
--------------------------------------------------------

  CREATE TABLE "COMUNE" 
   (	"ID" VARCHAR2(6 BYTE), 
	"IDENTE" VARCHAR2(3 BYTE), 
	"NOME" VARCHAR2(45 BYTE), 
	"CAP" VARCHAR2(5 BYTE), 
	"ZONAALT" VARCHAR2(1 BYTE), 
	"CODCATASTALE" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table DEROGA
--------------------------------------------------------

  CREATE TABLE "DEROGA" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDAUTORIZZAZIONE" NUMBER(*,0), 
	"PROTOCOLLO" VARCHAR2(100 BYTE), 
	"DATA" DATE, 
	"VOLUMEDEROGA" NUMBER(10,1), 
	"NOTE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table ENTE
--------------------------------------------------------

  CREATE TABLE "ENTE" 
   (	"ID" VARCHAR2(3 BYTE), 
	"IDREGIONE" VARCHAR2(2 BYTE), 
	"NOME" VARCHAR2(60 BYTE), 
	"SIGLA" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table ESERCENTE
--------------------------------------------------------

  CREATE TABLE "ESERCENTE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CODCCIA" VARCHAR2(50 BYTE), 
	"RAGSOC" VARCHAR2(50 BYTE), 
	"INDIRIZZO" VARCHAR2(250 BYTE), 
	"CAP" NUMBER(*,0), 
	"FRAZIONE" VARCHAR2(50 BYTE), 
	"IDCOMUNE" VARCHAR2(6 BYTE), 
	"CODICEFISCALE" VARCHAR2(16 BYTE), 
	"PARTITAIVA" VARCHAR2(16 BYTE), 
	"CODICEFISCALECOMPILATORE" VARCHAR2(16 BYTE), 
	"TELEFONO" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(120 BYTE), 
	"LEGALERAPPRESENTANTE" VARCHAR2(120 BYTE), 
	"DATIFALLIMENTO" VARCHAR2(2048 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table EXCEPTIONS
--------------------------------------------------------

  CREATE TABLE "EXCEPTIONS" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"GUID" RAW(16) DEFAULT SYS_GUID(), 
	"APPLICATIONNAME" VARCHAR2(50 BYTE), 
	"MACHINENAME" VARCHAR2(50 BYTE), 
	"CREATIONDATE" DATE, 
	"TYPE" VARCHAR2(100 BYTE), 
	"ISPROTECTED" NUMBER(1,0), 
	"HOST" VARCHAR2(100 BYTE), 
	"URL" VARCHAR2(500 BYTE), 
	"HTTPMETHOD" VARCHAR2(10 BYTE), 
	"IPADDRESS" VARCHAR2(40 BYTE), 
	"SOURCE" VARCHAR2(100 BYTE), 
	"MESSAGE" VARCHAR2(1000 BYTE), 
	"STATUSCODE" NUMBER(*,0), 
	"DELETIONDATE" DATE, 
	"ERRORHASH" NUMBER(*,0), 
	"DUPLICATECOUNT" NUMBER(*,0), 
	"SQL" CLOB, 
	"FULLJSON" CLOB, 
	"DETAIL" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
 LOB ("SQL") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("FULLJSON") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("DETAIL") STORE AS SECUREFILE (
  TABLESPACE "SYSAUX" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index EXCEPTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EXCEPTIONS_PK" ON "EXCEPTIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  Constraints for Table EXCEPTIONS
--------------------------------------------------------

  ALTER TABLE "EXCEPTIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" MODIFY ("GUID" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" MODIFY ("APPLICATIONNAME" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" MODIFY ("MACHINENAME" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" MODIFY ("ISPROTECTED" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" MODIFY ("DUPLICATECOUNT" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" ADD CONSTRAINT "EXCEPTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
--------------------------------------------------------
--  DDL for Table FABBISOGNO
--------------------------------------------------------

  CREATE TABLE "FABBISOGNO" 
   (	"IDPIANO" NUMBER(*,0), 
	"IDMATERIALE" NUMBER(*,0), 
	"FABBISOGNO" NUMBER(*,0), 
	"POTENZIALE" NUMBER(*,0), 
	"RESIDUO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table LANGUAGES
--------------------------------------------------------

  CREATE TABLE "LANGUAGES" 
   (	"ID" NUMBER(*,0) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"LANGUAGEID" VARCHAR2(10 BYTE), 
	"LANGUAGENAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table MATERIALE
--------------------------------------------------------

  CREATE TABLE "MATERIALE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIZIONE" VARCHAR2(60 BYTE), 
	"IDTIPOMATERIALE" NUMBER(*,0), 
	"TARIFFARIFERIMENTO" NUMBER(11,2), 
	"PESOSPECIFICORIFERIMENTO" NUMBER(11,2), 
	"NOMERISORSAMINERALEISTAT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table PIANO
--------------------------------------------------------

  CREATE TABLE "PIANO" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIZIONE" VARCHAR2(250 BYTE), 
	"IDENTE" VARCHAR2(3 BYTE), 
	"PROGRESSIVO" NUMBER(*,0), 
	"VARIANTE" NUMBER(*,0), 
	"DATAINIZIO" DATE, 
	"DATAFINE" DATE, 
	"NOTE" VARCHAR2(2048 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table PIANOAREA
--------------------------------------------------------

  CREATE TABLE "PIANOAREA" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDPIANO" NUMBER(*,0), 
	"IDAREA" NUMBER(*,0), 
	"TIPOSTATO" NUMBER(*,0), 
	"PROFMAX" NUMBER(9,1), 
	"SUP" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table POTENZIALE
--------------------------------------------------------

  CREATE TABLE "POTENZIALE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDMATERIALE" NUMBER(*,0), 
	"IDPIANOAREA" NUMBER(*,0), 
	"POTENZIALE" NUMBER(*,0), 
	"RESIDUO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table PRODOTTO
--------------------------------------------------------

  CREATE TABLE "PRODOTTO" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDRENDICONTO" NUMBER(*,0), 
	"IDMATERIALE" NUMBER(*,0), 
	"NUMEROMESIATTIVITA" NUMBER(9,2), 
	"TIPOLAVORAZIONE1" NUMBER(*,0), 
	"TIPOLAVORAZIONE2" NUMBER(*,0), 
	"TIPOLAVORAZIONE3" NUMBER(*,0), 
	"QUANTITAESTRATTA" NUMBER(10,1), 
	"ONERI" NUMBER(11,2), 
	"PESO" NUMBER(9,2), 
	"PESOSPECIFICO" NUMBER(9,2), 
	"PRIMALAVORAZIONE" NUMBER(1,0), 
	"QUANTITALAVORAZIONE" NUMBER(9,2), 
	"TIPOCOMMERCIALIZZAZIONE1" NUMBER(*,0), 
	"QUANTITA1" NUMBER(9,2), 
	"PREZZO1" NUMBER(11,2), 
	"UM1" VARCHAR2(10 BYTE), 
	"TIPOCOMMERCIALIZZAZIONE2" NUMBER(*,0), 
	"QUANTITA2" NUMBER(9,2), 
	"PREZZO2" NUMBER(11,2), 
	"UM2" VARCHAR2(10 BYTE), 
	"TIPOCOMMERCIALIZZAZIONE3" NUMBER(*,0), 
	"QUANTITA3" NUMBER(9,2), 
	"PREZZO3" NUMBER(11,2), 
	"UM3" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table PROROGA
--------------------------------------------------------

  CREATE TABLE "PROROGA" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDAUTORIZZAZIONE" NUMBER(*,0), 
	"PROTOCOLLO" VARCHAR2(100 BYTE), 
	"DATA" DATE, 
	"NUOVADATASISTEMAZIONE" DATE, 
	"NOTE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table REGIONE
--------------------------------------------------------

  CREATE TABLE "REGIONE" 
   (	"ID" VARCHAR2(2 BYTE), 
	"NOME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table RENDICONTO
--------------------------------------------------------

  CREATE TABLE "RENDICONTO" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDAUTORIZZAZIONE" NUMBER(*,0), 
	"IDSTRUTTURA" NUMBER(*,0), 
	"ANNO" NUMBER(*,0), 
	"NUMOPERAI" NUMBER(*,0), 
	"NUMAMMINISTRATIVI" NUMBER(*,0), 
	"NUMTECNICI" NUMBER(*,0), 
	"NUMADDETTI" NUMBER(*,0), 
	"ORELAVORATE" NUMBER(9,2), 
	"NUMEROMESIATTIVITA" NUMBER(9,2), 
	"VOLACQUAESTRAZIONE" NUMBER(11,2), 
	"VOLACQUALAVORAZIONI" NUMBER(11,2), 
	"STRUTTDEPMATINUT" NUMBER(1,0), 
	"ESPLOSIVO" NUMBER(11,2), 
	"DETONATORI" NUMBER(*,0), 
	"FILOELICOIDALE" NUMBER(11,2), 
	"MEZZOMECCANICO" NUMBER(11,2), 
	"MICCELENTACOMBUSTIONE" NUMBER(11,2), 
	"QUANTITAKW" NUMBER(11,2), 
	"IMPORTOKW" NUMBER(11,2), 
	"QUANTITAGASOLIO" NUMBER(11,2), 
	"IMPORTOGASOLIO" NUMBER(11,2), 
	"QUANTITABENZINA" NUMBER(11,2), 
	"IMPORTOBENZINA" NUMBER(11,2), 
	"DESCRIZIONEALTREFONTIENERGIA" VARCHAR2(100 BYTE), 
	"UNITAMISURAALTREFONTIENERGIA" VARCHAR2(50 BYTE), 
	"QUANTITAALTREFONTIENERGIA" NUMBER(11,2), 
	"IMPORTOALTREFONTIENERGIA" NUMBER(11,2), 
	"LAVORATOM3" NUMBER(11,2), 
	"LAVORATOQ" NUMBER(11,2), 
	"METODOLAVORAZIONE" VARCHAR2(1 BYTE), 
	"MATERIALETRADIZIONALE" NUMBER(1,0), 
	"MATERIALERICICLATO" NUMBER(1,0), 
	"TIPOLOGIAIMPIANTO" VARCHAR2(1 BYTE), 
	"DIRITTOPROP" NUMBER(11,2), 
	"AREALAVORAZIONE" NUMBER(11,2), 
	"AREACOLTIVAZIONE" NUMBER(11,2), 
	"DIRETTORERESPONSABILE" VARCHAR2(100 BYTE), 
	"SORVEGLIANTE" VARCHAR2(100 BYTE), 
	"RESPONSABILESICUREZZA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table RENDICONTOAPPROVVIGIONAMENTO
--------------------------------------------------------

  CREATE TABLE "RENDICONTOAPPROVVIGIONAMENTO" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDRENDICONTO" NUMBER(*,0), 
	"TIPOAPPROVVIGIONAMENTO" NUMBER(*,0), 
	"IDSTRUTTURACAVA" NUMBER(*,0), 
	"QTAAPPROV" NUMBER(9,1), 
	"NOTE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table RENDICONTODESTINAZIONETERRITORIALE
--------------------------------------------------------

  CREATE TABLE "RENDICONTODESTINAZIONETERRITORIALE" 
   (	"IDRENDICONTO" NUMBER(*,0), 
	"TIPODESTINAZIONETERRITORIALE" NUMBER(*,0), 
	"PERCENTUALE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table RENDICONTODESTINAZIONEUSO
--------------------------------------------------------

  CREATE TABLE "RENDICONTODESTINAZIONEUSO" 
   (	"IDRENDICONTO" NUMBER(*,0), 
	"TIPODESTINAZIONEUSO" NUMBER(*,0), 
	"PERCENTUALE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table ROLEPERMISSIONS
--------------------------------------------------------

  CREATE TABLE "ROLEPERMISSIONS" 
   (	"ROLEPERMISSIONID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ROLEID" NUMBER(*,0), 
	"PERMISSIONKEY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "ROLES" 
   (	"ROLEID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ROLENAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
;
--------------------------------------------------------
--  DDL for Table SCARTO
--------------------------------------------------------

  CREATE TABLE "SCARTO" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDRENDICONTO" NUMBER(*,0), 
	"TIPOSCARTO" NUMBER(*,0), 
	"PESO" NUMBER(9,2), 
	"VOLUME" NUMBER(9,2), 
	"DESCRIZIONEALTRO" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table STRUTTURA
--------------------------------------------------------

  CREATE TABLE "STRUTTURA" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IDCOMUNE" VARCHAR2(6 BYTE), 
	"TIPOPOSIZIONE" NUMBER(*,0), 
	"TIPODISSESTO" NUMBER(*,0), 
	"TIPOCOLTIVAZIONE" NUMBER(*,0), 
	"PROGRESSIVO" NUMBER(*,0), 
	"NOME" VARCHAR2(250 BYTE), 
	"FRAZIONE" VARCHAR2(50 BYTE), 
	"CATASTOPROVINCIALE" VARCHAR2(50 BYTE), 
	"COORDINATAX" NUMBER(18,6), 
	"COORDINATAY" NUMBER(18,6), 
	"VINCOLOAMBIENTALE" NUMBER(*,0), 
	"AREAPROTETTA" NUMBER(1,0), 
	"PROFONDITAFALDA" NUMBER(9,2), 
	"TIPOSTRUTTURA" NUMBER(*,0), 
	"TIPOIMPIANTO" NUMBER(*,0), 
	"DATAINSTALLAZIONEIMPIANTO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table TIPOMATERIALE
--------------------------------------------------------

  CREATE TABLE "TIPOMATERIALE" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIZIONE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table USERPERMISSIONS
--------------------------------------------------------

  CREATE TABLE "USERPERMISSIONS" 
   (	"USERPERMISSIONID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERID" NUMBER(*,0), 
	"PERMISSIONKEY" VARCHAR2(100 BYTE), 
	"GRANTED" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
;
--------------------------------------------------------
--  DDL for Table USERPREFERENCES
--------------------------------------------------------

  CREATE TABLE "USERPREFERENCES" 
   (	"USERPREFERENCEID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERID" NUMBER(*,0), 
	"PREFERENCETYPE" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"VALUE" VARCHAR2(2048 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
;
--------------------------------------------------------
--  DDL for Table USERROLES
--------------------------------------------------------

  CREATE TABLE "USERROLES" 
   (	"USERROLEID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERID" NUMBER(*,0), 
	"ROLEID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "USERS" 
   (	"USERID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERNAME" VARCHAR2(100 BYTE), 
	"DISPLAYNAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"SOURCE" VARCHAR2(4 BYTE), 
	"PASSWORDHASH" VARCHAR2(86 BYTE), 
	"PASSWORDSALT" VARCHAR2(10 BYTE), 
	"LASTDIRECTORYUPDATE" DATE, 
	"USERIMAGE" VARCHAR2(100 BYTE), 
	"INSERTDATE" DATE, 
	"INSERTUSERID" NUMBER(*,0), 
	"UPDATEDATE" DATE, 
	"UPDATEUSERID" NUMBER(*,0), 
	"ISACTIVE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Table VERSIONINFO
--------------------------------------------------------

  CREATE TABLE "VERSIONINFO" 
   (	"VERSION" NUMBER(*,0), 
	"APPLIEDON" DATE, 
	"DESCRIPTION" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
;
--------------------------------------------------------
--  DDL for View CAVA
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CAVA" ("ID", "IDCOMUNE", "TIPOPOSIZIONE", "TIPODISSESTO", "TIPOCOLTIVAZIONE", "PROGRESSIVO", "NOME", "FRAZIONE", "CATASTOPROVINCIALE", "COORDINATAX", "COORDINATAY", "VINCOLOAMBIENTALE", "AREAPROTETTA", "PROFONDITAFALDA", "TIPOSTRUTTURA") AS 
  SELECT        ID, IDComune, TipoPosizione, TipoDissesto, TipoColtivazione, Progressivo, Nome, Frazione, CatastoProvinciale, CoordinataX, CoordinataY, VincoloAmbientale, AreaProtetta, ProfonditaFalda, TipoStruttura
FROM            Struttura
WHERE        (TipoStruttura = 1)
;
--------------------------------------------------------
--  DDL for View IMPIANTO
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "IMPIANTO" ("ID", "IDCOMUNE", "PROGRESSIVO", "NOME", "FRAZIONE", "CATASTOPROVINCIALE", "COORDINATAX", "COORDINATAY", "TIPOIMPIANTO", "DATAINSTALLAZIONEIMPIANTO", "TIPOSTRUTTURA") AS 
  SELECT        ID, IDComune, Progressivo, Nome, Frazione, CatastoProvinciale, CoordinataX, CoordinataY, TipoImpianto, DataInstallazioneImpianto, TipoStruttura
FROM            Struttura
WHERE        (TipoStruttura = 2)
;
--------------------------------------------------------
--  DDL for View MINIERA
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "MINIERA" ("ID", "IDCOMUNE", "TIPOPOSIZIONE", "TIPODISSESTO", "TIPOCOLTIVAZIONE", "PROGRESSIVO", "NOME", "FRAZIONE", "CATASTOPROVINCIALE", "COORDINATAX", "COORDINATAY", "VINCOLOAMBIENTALE", "AREAPROTETTA", "PROFONDITAFALDA", "TIPOSTRUTTURA") AS 
  SELECT        ID, IDComune, TipoPosizione, TipoDissesto, TipoColtivazione, Progressivo, Nome, Frazione, CatastoProvinciale, CoordinataX, CoordinataY, VincoloAmbientale, AreaProtetta, ProfonditaFalda, TipoStruttura
FROM            Struttura
WHERE        (TipoStruttura = 3)
;
--------------------------------------------------------
--  DDL for View RENDICONTOEXT
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "RENDICONTOEXT" ("ID", "IDAUTORIZZAZIONE", "IDSTRUTTURA", "ANNO", "NUMOPERAI", "NUMAMMINISTRATIVI", "NUMTECNICI", "NUMADDETTI", "ORELAVORATE", "NUMEROMESIATTIVITA", "VOLACQUAESTRAZIONE", "VOLACQUALAVORAZIONI", "STRUTTDEPMATINUT", "ESPLOSIVO", "DETONATORI", "FILOELICOIDALE", "MEZZOMECCANICO", "MICCELENTACOMBUSTIONE", "QUANTITAKW", "IMPORTOKW", "QUANTITAGASOLIO", "IMPORTOGASOLIO", "QUANTITABENZINA", "IMPORTOBENZINA", "DESCRIZIONEALTREFONTIENERGIA", "UNITAMISURAALTREFONTIENERGIA", "QUANTITAALTREFONTIENERGIA", "IMPORTOALTREFONTIENERGIA", "LAVORATOM3", "LAVORATOQ", "METODOLAVORAZIONE", "MATERIALETRADIZIONALE", "MATERIALERICICLATO", "TIPOLOGIAIMPIANTO", "DIRITTOPROP", "AREALAVORAZIONE", "AREACOLTIVAZIONE", "DIRETTORERESPONSABILE", "SORVEGLIANTE", "RESPONSABILESICUREZZA", "COMUNE", "DESCRIZIONE", "TIPOSTRUTTURA") AS 
  SELECT r."ID",r."IDAUTORIZZAZIONE",r."IDSTRUTTURA",r."ANNO",r."NUMOPERAI",r."NUMAMMINISTRATIVI",r."NUMTECNICI",r."NUMADDETTI",r."ORELAVORATE",r."NUMEROMESIATTIVITA",r."VOLACQUAESTRAZIONE",r."VOLACQUALAVORAZIONI",r."STRUTTDEPMATINUT",r."ESPLOSIVO",r."DETONATORI",r."FILOELICOIDALE",r."MEZZOMECCANICO",r."MICCELENTACOMBUSTIONE",r."QUANTITAKW",r."IMPORTOKW",r."QUANTITAGASOLIO",r."IMPORTOGASOLIO",r."QUANTITABENZINA",r."IMPORTOBENZINA",r."DESCRIZIONEALTREFONTIENERGIA",r."UNITAMISURAALTREFONTIENERGIA",r."QUANTITAALTREFONTIENERGIA",r."IMPORTOALTREFONTIENERGIA",r."LAVORATOM3",r."LAVORATOQ",r."METODOLAVORAZIONE",r."MATERIALETRADIZIONALE",r."MATERIALERICICLATO",r."TIPOLOGIAIMPIANTO",r."DIRITTOPROP",r."AREALAVORAZIONE",r."AREACOLTIVAZIONE",r."DIRETTORERESPONSABILE",r."SORVEGLIANTE",r."RESPONSABILESICUREZZA", c.Nome Comune, s.Nome || '-' || a.NumeroAtto || ' del ' || TO_CHAR(DataAutorizzazione) Descrizione,
	s.TipoStruttura 
FROM     
	Rendiconto r 
		inner join Autorizzazione a on r.IDAutorizzazione = a.ID 
		inner join Struttura s on a.IDStruttura = s.id
		inner join Comune c on s.IDComune = c.ID
;
--------------------------------------------------------
--  DDL for Index AREA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AREA_PK" ON "AREA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index ATTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ATTO_PK" ON "ATTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index AUTORIZZAZIONEMATERIALE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUTORIZZAZIONEMATERIALE_PK" ON "AUTORIZZAZIONEMATERIALE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index AUTORIZZAZIONE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AUTORIZZAZIONE_PK" ON "AUTORIZZAZIONE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index COMUNE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMUNE_PK" ON "COMUNE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index DEROGA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEROGA_PK" ON "DEROGA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index ENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ENTE_PK" ON "ENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index ESERCENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ESERCENTE_PK" ON "ESERCENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index EXCEPTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EXCEPTIONS_PK" ON "EXCEPTIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index FABBISOGNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FABBISOGNO_PK" ON "FABBISOGNO" ("IDMATERIALE", "IDPIANO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index MATERIALE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MATERIALE_PK" ON "MATERIALE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index PIANOAREA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIANOAREA_PK" ON "PIANOAREA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index PIANO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIANO_PK" ON "PIANO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index POTENZIALE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "POTENZIALE_PK" ON "POTENZIALE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index PRODOTTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRODOTTO_PK" ON "PRODOTTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index PROROGA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROROGA_PK" ON "PROROGA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index REGIONE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REGIONE_PK" ON "REGIONE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index RENDICONTOAPPROVVIGIONAMENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENDICONTOAPPROVVIGIONAMENTO_PK" ON "RENDICONTOAPPROVVIGIONAMENTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index RENDICONTODESTINAZIONETERRITORIALE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENDICONTODESTINAZIONETERRITORIALE_PK" ON "RENDICONTODESTINAZIONETERRITORIALE" ("IDRENDICONTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index RENDICONTODESTINAZIONEUSO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENDICONTODESTINAZIONEUSO_PK" ON "RENDICONTODESTINAZIONEUSO" ("IDRENDICONTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index RENDICONTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RENDICONTO_PK" ON "RENDICONTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index ROLEPERMISSIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROLEPERMISSIONS_PK" ON "ROLEPERMISSIONS" ("ROLEPERMISSIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROLES_PK" ON "ROLES" ("ROLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
;
--------------------------------------------------------
--  DDL for Index SCARTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCARTO_PK" ON "SCARTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index STRUTTURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STRUTTURA_PK" ON "STRUTTURA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index TIPOMATERIALE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIPOMATERIALE_PK" ON "TIPOMATERIALE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index USERPERMISSIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERPERMISSIONS_PK" ON "USERPERMISSIONS" ("USERPERMISSIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
;
--------------------------------------------------------
--  DDL for Index USERPREFERENCES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERPREFERENCES_PK" ON "USERPREFERENCES" ("USERPREFERENCEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
;
--------------------------------------------------------
--  DDL for Index USERROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERROLES_PK" ON "USERROLES" ("USERROLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USERS_PK" ON "USERS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
;
--------------------------------------------------------
--  DDL for Index VERSIONINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VERSIONINFO_PK" ON "VERSIONINFO" ("VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
;

--------------------------------------------------------
--  Constraints for Table AREA
--------------------------------------------------------

  ALTER TABLE "AREA" ADD CONSTRAINT "TEST" UNIQUE ("NOME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "AREA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AREA" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "AREA" ADD CONSTRAINT "AREA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
--------------------------------------------------------
--  Constraints for Table ATTO
--------------------------------------------------------

  ALTER TABLE "ATTO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ATTO" MODIFY ("NUMATTO" NOT NULL ENABLE);
  ALTER TABLE "ATTO" MODIFY ("DATAATTO" NOT NULL ENABLE);
  ALTER TABLE "ATTO" MODIFY ("IDPIANO" NOT NULL ENABLE);
  ALTER TABLE "ATTO" ADD CONSTRAINT "ATTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTORIZZAZIONE
--------------------------------------------------------

  ALTER TABLE "AUTORIZZAZIONE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AUTORIZZAZIONE" ADD CONSTRAINT "AUTORIZZAZIONE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTORIZZAZIONEMATERIALE
--------------------------------------------------------

  ALTER TABLE "AUTORIZZAZIONEMATERIALE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "AUTORIZZAZIONEMATERIALE" MODIFY ("IDAUTORIZZAZIONE" NOT NULL ENABLE);
  ALTER TABLE "AUTORIZZAZIONEMATERIALE" MODIFY ("IDMATERIALE" NOT NULL ENABLE);
  ALTER TABLE "AUTORIZZAZIONEMATERIALE" ADD CONSTRAINT "AUTORIZZAZIONEMATERIALE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
--------------------------------------------------------
--  Constraints for Table COMUNE
--------------------------------------------------------

  ALTER TABLE "COMUNE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "COMUNE" ADD CONSTRAINT "COMUNE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
--------------------------------------------------------
--  Constraints for Table DEROGA
--------------------------------------------------------

  ALTER TABLE "DEROGA" ADD CONSTRAINT "DEROGA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "DEROGA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEROGA" MODIFY ("IDAUTORIZZAZIONE" NOT NULL ENABLE);
  ALTER TABLE "DEROGA" MODIFY ("VOLUMEDEROGA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENTE
--------------------------------------------------------

  ALTER TABLE "ENTE" ADD CONSTRAINT "ENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "ENTE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESERCENTE
--------------------------------------------------------

  ALTER TABLE "ESERCENTE" ADD CONSTRAINT "ESERCENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "ESERCENTE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXCEPTIONS
--------------------------------------------------------

  ALTER TABLE "EXCEPTIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" MODIFY ("GUID" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" MODIFY ("APPLICATIONNAME" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" MODIFY ("MACHINENAME" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" MODIFY ("CREATIONDATE" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" MODIFY ("ISPROTECTED" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" MODIFY ("DUPLICATECOUNT" NOT NULL ENABLE);
  ALTER TABLE "EXCEPTIONS" ADD CONSTRAINT "EXCEPTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
--------------------------------------------------------
--  Constraints for Table FABBISOGNO
--------------------------------------------------------

  ALTER TABLE "FABBISOGNO" ADD CONSTRAINT "FABBISOGNO_PK" PRIMARY KEY ("IDMATERIALE", "IDPIANO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "FABBISOGNO" MODIFY ("IDPIANO" NOT NULL ENABLE);
  ALTER TABLE "FABBISOGNO" MODIFY ("IDMATERIALE" NOT NULL ENABLE);
  ALTER TABLE "FABBISOGNO" MODIFY ("FABBISOGNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LANGUAGES
--------------------------------------------------------

  ALTER TABLE "LANGUAGES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "LANGUAGES" MODIFY ("LANGUAGEID" NOT NULL ENABLE);
  ALTER TABLE "LANGUAGES" MODIFY ("LANGUAGENAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATERIALE
--------------------------------------------------------

  ALTER TABLE "MATERIALE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MATERIALE" MODIFY ("DESCRIZIONE" NOT NULL ENABLE);
  ALTER TABLE "MATERIALE" ADD CONSTRAINT "MATERIALE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
--------------------------------------------------------
--  Constraints for Table PIANO
--------------------------------------------------------

  ALTER TABLE "PIANO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PIANO" MODIFY ("DESCRIZIONE" NOT NULL ENABLE);
  ALTER TABLE "PIANO" MODIFY ("IDENTE" NOT NULL ENABLE);
  ALTER TABLE "PIANO" MODIFY ("PROGRESSIVO" NOT NULL ENABLE);
  ALTER TABLE "PIANO" MODIFY ("VARIANTE" NOT NULL ENABLE);
  ALTER TABLE "PIANO" MODIFY ("DATAINIZIO" NOT NULL ENABLE);
  ALTER TABLE "PIANO" MODIFY ("DATAFINE" NOT NULL ENABLE);
  ALTER TABLE "PIANO" ADD CONSTRAINT "PIANO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
--------------------------------------------------------
--  Constraints for Table PIANOAREA
--------------------------------------------------------

  ALTER TABLE "PIANOAREA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PIANOAREA" MODIFY ("IDPIANO" NOT NULL ENABLE);
  ALTER TABLE "PIANOAREA" MODIFY ("IDAREA" NOT NULL ENABLE);
  ALTER TABLE "PIANOAREA" ADD CONSTRAINT "PIANOAREA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
--------------------------------------------------------
--  Constraints for Table POTENZIALE
--------------------------------------------------------

  ALTER TABLE "POTENZIALE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "POTENZIALE" MODIFY ("IDMATERIALE" NOT NULL ENABLE);
  ALTER TABLE "POTENZIALE" MODIFY ("IDPIANOAREA" NOT NULL ENABLE);
  ALTER TABLE "POTENZIALE" ADD CONSTRAINT "POTENZIALE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODOTTO
--------------------------------------------------------

  ALTER TABLE "PRODOTTO" ADD CONSTRAINT "PRODOTTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "PRODOTTO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PRODOTTO" MODIFY ("IDRENDICONTO" NOT NULL ENABLE);
  ALTER TABLE "PRODOTTO" MODIFY ("IDMATERIALE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROROGA
--------------------------------------------------------

  ALTER TABLE "PROROGA" ADD CONSTRAINT "PROROGA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "PROROGA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROROGA" MODIFY ("IDAUTORIZZAZIONE" NOT NULL ENABLE);
  ALTER TABLE "PROROGA" MODIFY ("NUOVADATASISTEMAZIONE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REGIONE
--------------------------------------------------------

  ALTER TABLE "REGIONE" ADD CONSTRAINT "REGIONE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "REGIONE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RENDICONTO
--------------------------------------------------------

  ALTER TABLE "RENDICONTO" ADD CONSTRAINT "RENDICONTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "RENDICONTO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RENDICONTOAPPROVVIGIONAMENTO
--------------------------------------------------------

  ALTER TABLE "RENDICONTOAPPROVVIGIONAMENTO" ADD CONSTRAINT "RENDICONTOAPPROVVIGIONAMENTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "RENDICONTOAPPROVVIGIONAMENTO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RENDICONTOAPPROVVIGIONAMENTO" MODIFY ("IDRENDICONTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RENDICONTODESTINAZIONETERRITORIALE
--------------------------------------------------------

  ALTER TABLE "RENDICONTODESTINAZIONETERRITORIALE" ADD CONSTRAINT "RENDICONTODESTINAZIONETERRITORIALE_PK" PRIMARY KEY ("IDRENDICONTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "RENDICONTODESTINAZIONETERRITORIALE" MODIFY ("IDRENDICONTO" NOT NULL ENABLE);
  ALTER TABLE "RENDICONTODESTINAZIONETERRITORIALE" MODIFY ("TIPODESTINAZIONETERRITORIALE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RENDICONTODESTINAZIONEUSO
--------------------------------------------------------

  ALTER TABLE "RENDICONTODESTINAZIONEUSO" ADD CONSTRAINT "RENDICONTODESTINAZIONEUSO_PK" PRIMARY KEY ("IDRENDICONTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "RENDICONTODESTINAZIONEUSO" MODIFY ("IDRENDICONTO" NOT NULL ENABLE);
  ALTER TABLE "RENDICONTODESTINAZIONEUSO" MODIFY ("TIPODESTINAZIONEUSO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLEPERMISSIONS
--------------------------------------------------------

  ALTER TABLE "ROLEPERMISSIONS" ADD CONSTRAINT "ROLEPERMISSIONS_PK" PRIMARY KEY ("ROLEPERMISSIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
 ENABLE;
  ALTER TABLE "ROLEPERMISSIONS" MODIFY ("ROLEPERMISSIONID" NOT NULL ENABLE);
  ALTER TABLE "ROLEPERMISSIONS" MODIFY ("ROLEID" NOT NULL ENABLE);
  ALTER TABLE "ROLEPERMISSIONS" MODIFY ("PERMISSIONKEY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("ROLEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
 ENABLE;
  ALTER TABLE "ROLES" MODIFY ("ROLEID" NOT NULL ENABLE);
  ALTER TABLE "ROLES" MODIFY ("ROLENAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SCARTO
--------------------------------------------------------

  ALTER TABLE "SCARTO" ADD CONSTRAINT "SCARTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "SCARTO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SCARTO" MODIFY ("IDRENDICONTO" NOT NULL ENABLE);
  ALTER TABLE "SCARTO" MODIFY ("TIPOSCARTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STRUTTURA
--------------------------------------------------------

  ALTER TABLE "STRUTTURA" ADD CONSTRAINT "STRUTTURA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "STRUTTURA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "STRUTTURA" MODIFY ("TIPOSTRUTTURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPOMATERIALE
--------------------------------------------------------

  ALTER TABLE "TIPOMATERIALE" ADD CONSTRAINT "TIPOMATERIALE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "TIPOMATERIALE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERPERMISSIONS
--------------------------------------------------------

  ALTER TABLE "USERPERMISSIONS" ADD CONSTRAINT "USERPERMISSIONS_PK" PRIMARY KEY ("USERPERMISSIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
 ENABLE;
  ALTER TABLE "USERPERMISSIONS" MODIFY ("USERPERMISSIONID" NOT NULL ENABLE);
  ALTER TABLE "USERPERMISSIONS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "USERPERMISSIONS" MODIFY ("PERMISSIONKEY" NOT NULL ENABLE);
  ALTER TABLE "USERPERMISSIONS" MODIFY ("GRANTED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERPREFERENCES
--------------------------------------------------------

  ALTER TABLE "USERPREFERENCES" ADD CONSTRAINT "USERPREFERENCES_PK" PRIMARY KEY ("USERPREFERENCEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
 ENABLE;
  ALTER TABLE "USERPREFERENCES" MODIFY ("USERPREFERENCEID" NOT NULL ENABLE);
  ALTER TABLE "USERPREFERENCES" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "USERPREFERENCES" MODIFY ("PREFERENCETYPE" NOT NULL ENABLE);
  ALTER TABLE "USERPREFERENCES" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERROLES
--------------------------------------------------------

  ALTER TABLE "USERROLES" ADD CONSTRAINT "USERROLES_PK" PRIMARY KEY ("USERROLEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
 ENABLE;
  ALTER TABLE "USERROLES" MODIFY ("USERROLEID" NOT NULL ENABLE);
  ALTER TABLE "USERROLES" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "USERROLES" MODIFY ("ROLEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 ENABLE;
  ALTER TABLE "USERS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("DISPLAYNAME" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("SOURCE" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("PASSWORDHASH" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("PASSWORDSALT" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("INSERTDATE" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("INSERTUSERID" NOT NULL ENABLE);
  ALTER TABLE "USERS" MODIFY ("ISACTIVE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VERSIONINFO
--------------------------------------------------------

  ALTER TABLE "VERSIONINFO" ADD CONSTRAINT "VERSIONINFO_PK" PRIMARY KEY ("VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
 ENABLE;
  ALTER TABLE "VERSIONINFO" MODIFY ("VERSION" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ATTO
--------------------------------------------------------

  ALTER TABLE "ATTO" ADD CONSTRAINT "ATTO_FK1" FOREIGN KEY ("IDPIANO")
	  REFERENCES "PIANO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTORIZZAZIONE
--------------------------------------------------------

  ALTER TABLE "AUTORIZZAZIONE" ADD CONSTRAINT "AUTORIZZAZIONE_FK1" FOREIGN KEY ("IDPIANO")
	  REFERENCES "PIANO" ("ID") ENABLE;
  ALTER TABLE "AUTORIZZAZIONE" ADD CONSTRAINT "AUTORIZZAZIONE_FK2" FOREIGN KEY ("IDPIANOAREA")
	  REFERENCES "PIANOAREA" ("ID") ENABLE;
  ALTER TABLE "AUTORIZZAZIONE" ADD CONSTRAINT "AUTORIZZAZIONE_FK3" FOREIGN KEY ("IDSTRUTTURA")
	  REFERENCES "STRUTTURA" ("ID") ENABLE;
  ALTER TABLE "AUTORIZZAZIONE" ADD CONSTRAINT "AUTORIZZAZIONE_FK4" FOREIGN KEY ("IDESERCENTE")
	  REFERENCES "ESERCENTE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTORIZZAZIONEMATERIALE
--------------------------------------------------------

  ALTER TABLE "AUTORIZZAZIONEMATERIALE" ADD CONSTRAINT "AUTORIZZAZIONEMATERIALE_FK1" FOREIGN KEY ("IDAUTORIZZAZIONE")
	  REFERENCES "AUTORIZZAZIONE" ("ID") ENABLE;
  ALTER TABLE "AUTORIZZAZIONEMATERIALE" ADD CONSTRAINT "AUTORIZZAZIONEMATERIALE_FK2" FOREIGN KEY ("IDMATERIALE")
	  REFERENCES "MATERIALE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMUNE
--------------------------------------------------------

  ALTER TABLE "COMUNE" ADD CONSTRAINT "COMUNE_FK1" FOREIGN KEY ("IDENTE")
	  REFERENCES "ENTE" ("ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table DEROGA
--------------------------------------------------------

  ALTER TABLE "DEROGA" ADD CONSTRAINT "DEROGA_FK1" FOREIGN KEY ("IDAUTORIZZAZIONE")
	  REFERENCES "AUTORIZZAZIONE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENTE
--------------------------------------------------------

  ALTER TABLE "ENTE" ADD CONSTRAINT "ENTE_FK1" FOREIGN KEY ("IDREGIONE")
	  REFERENCES "REGIONE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FABBISOGNO
--------------------------------------------------------

  ALTER TABLE "FABBISOGNO" ADD CONSTRAINT "FABBISOGNO_FK1" FOREIGN KEY ("IDPIANO")
	  REFERENCES "PIANO" ("ID") ENABLE;
  ALTER TABLE "FABBISOGNO" ADD CONSTRAINT "FABBISOGNO_FK2" FOREIGN KEY ("IDMATERIALE")
	  REFERENCES "MATERIALE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATERIALE
--------------------------------------------------------

  ALTER TABLE "MATERIALE" ADD CONSTRAINT "MATERIALE_FK1" FOREIGN KEY ("IDTIPOMATERIALE")
	  REFERENCES "TIPOMATERIALE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PIANO
--------------------------------------------------------

  ALTER TABLE "PIANO" ADD CONSTRAINT "PIANO_FK1" FOREIGN KEY ("IDENTE")
	  REFERENCES "ENTE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PIANOAREA
--------------------------------------------------------

  ALTER TABLE "PIANOAREA" ADD CONSTRAINT "PIANOAREA_FK1" FOREIGN KEY ("IDPIANO")
	  REFERENCES "PIANO" ("ID") ENABLE;
  ALTER TABLE "PIANOAREA" ADD CONSTRAINT "PIANOAREA_FK2" FOREIGN KEY ("IDAREA")
	  REFERENCES "AREA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POTENZIALE
--------------------------------------------------------

  ALTER TABLE "POTENZIALE" ADD CONSTRAINT "POTENZIALE_FK1" FOREIGN KEY ("IDMATERIALE")
	  REFERENCES "MATERIALE" ("ID") ENABLE;
  ALTER TABLE "POTENZIALE" ADD CONSTRAINT "POTENZIALE_FK2" FOREIGN KEY ("IDPIANOAREA")
	  REFERENCES "PIANOAREA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODOTTO
--------------------------------------------------------

  ALTER TABLE "PRODOTTO" ADD CONSTRAINT "PRODOTTO_FK1" FOREIGN KEY ("IDRENDICONTO")
	  REFERENCES "RENDICONTO" ("ID") ENABLE;
  ALTER TABLE "PRODOTTO" ADD CONSTRAINT "PRODOTTO_FK2" FOREIGN KEY ("IDMATERIALE")
	  REFERENCES "MATERIALE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROROGA
--------------------------------------------------------

  ALTER TABLE "PROROGA" ADD CONSTRAINT "PROROGA_FK1" FOREIGN KEY ("IDAUTORIZZAZIONE")
	  REFERENCES "AUTORIZZAZIONE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RENDICONTO
--------------------------------------------------------

  ALTER TABLE "RENDICONTO" ADD CONSTRAINT "RENDICONTO_FK1" FOREIGN KEY ("IDAUTORIZZAZIONE")
	  REFERENCES "AUTORIZZAZIONE" ("ID") ENABLE;
  ALTER TABLE "RENDICONTO" ADD CONSTRAINT "RENDICONTO_FK2" FOREIGN KEY ("IDSTRUTTURA")
	  REFERENCES "STRUTTURA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RENDICONTOAPPROVVIGIONAMENTO
--------------------------------------------------------

  ALTER TABLE "RENDICONTOAPPROVVIGIONAMENTO" ADD CONSTRAINT "RENDICONTOAPPROVVIGIONAMENTO_FK1" FOREIGN KEY ("IDRENDICONTO")
	  REFERENCES "RENDICONTO" ("ID") ENABLE;
  ALTER TABLE "RENDICONTOAPPROVVIGIONAMENTO" ADD CONSTRAINT "RENDICONTOAPPROVVIGIONAMENTO_FK2" FOREIGN KEY ("IDSTRUTTURACAVA")
	  REFERENCES "STRUTTURA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROLEPERMISSIONS
--------------------------------------------------------

  ALTER TABLE "ROLEPERMISSIONS" ADD CONSTRAINT "ROLEPERMISSIONS_FK1" FOREIGN KEY ("ROLEID")
	  REFERENCES "ROLES" ("ROLEID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCARTO
--------------------------------------------------------

  ALTER TABLE "SCARTO" ADD CONSTRAINT "SCARTO_FK1" FOREIGN KEY ("IDRENDICONTO")
	  REFERENCES "RENDICONTO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STRUTTURA
--------------------------------------------------------

  ALTER TABLE "STRUTTURA" ADD CONSTRAINT "STRUTTURA_FK1" FOREIGN KEY ("IDCOMUNE")
	  REFERENCES "COMUNE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERPERMISSIONS
--------------------------------------------------------

  ALTER TABLE "USERPERMISSIONS" ADD CONSTRAINT "USERPERMISSIONS_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "USERS" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERPREFERENCES
--------------------------------------------------------

  ALTER TABLE "USERPREFERENCES" ADD CONSTRAINT "USERPREFERENCES_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "USERS" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERROLES
--------------------------------------------------------

  ALTER TABLE "USERROLES" ADD CONSTRAINT "USERROLES_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "USERS" ("USERID") ENABLE;
  ALTER TABLE "USERROLES" ADD CONSTRAINT "USERROLES_FK2" FOREIGN KEY ("ROLEID")
	  REFERENCES "ROLES" ("ROLEID") ENABLE;
