//[assembly: NavigationLink(int.MaxValue, "Default/Potenziale", typeof(MyPages.PotenzialeController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Esercente", typeof(MyPages.EsercenteController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Comune", typeof(MyPages.ComuneController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Cava", typeof(MyPages.CavaController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Impianto", typeof(MyPages.ImpiantoController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Miniera", typeof(MyPages.MinieraController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Autorizzazione", typeof(MyPages.AutorizzazioneController), icon: null)]
////[assembly: NavigationLink(int.MaxValue, "Default/Autorizzazione Materiale", typeof(MyPages.AutorizzazioneMaterialeController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Deroga", typeof(MyPages.DerogaController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Proroga", typeof(MyPages.ProrogaController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Prodotto", typeof(MyPages.ProdottoController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Rendiconto", typeof(MyPages.RendicontoController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Scarto", typeof(MyPages.ScartoController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Rendiconto Approvvigionamento", typeof(MyPages.RendicontoApprovvigionamentoController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Rendiconto Destinazione Territoriale", typeof(MyPages.RendicontoDestinazioneTerritorialeController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Rendiconto Destinazione Uso", typeof(MyPages.RendicontoDestinazioneUsoController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Ente", typeof(MyPages.EnteController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Default/Regione", typeof(MyPages.RegioneController), icon: null)]